-- Fall 2026 season data imported from the original Google Doc (Sept 26, 2026).

insert into public.season (id, name, rules, playoffs) values (1, 'Fall 2026 Ladder', array['You''re responsible for contacting your weekly opponent, setting a match date and time, and booking a court.', 'Matches are best 2 out of 3 sets, with a 10-point tiebreak in place of a third set. Other formats (8-game pro set, no-ad, full third set, etc.) are fine if both players agree before play starts.', 'If you can''t play a match during its scheduled week, you can make it up any time before the end of the season.', 'Report your score here as soon as the match is done. Either player can report it, and either can correct it.', 'The home player brings a new can of balls unless you agree otherwise.', 'A playoff follows the regular season, seeded by overall record. Draw size and start date TBD.', 'Have fun!'], 'TBD');

insert into public.weeks (n, starts_on, ends_on) values (1, '2026-09-14', '2026-09-20'), (2, '2026-09-21', '2026-09-27'), (3, '2026-09-28', '2026-10-04'), (4, '2026-10-05', '2026-10-11'), (5, '2026-10-12', '2026-10-18');

insert into public.players (id, name) values
  ('adam-versenyi', 'Adam Versenyi'),
  ('adam-zinn', 'Adam Zinn'),
  ('andrew-barrett', 'Andrew Barrett'),
  ('andrew-kay', 'Andrew Kay'),
  ('andy-galdi', 'Andy Galdi'),
  ('cary-levine', 'Cary Levine'),
  ('chris-petree', 'Chris Petree'),
  ('clark-troy', 'Clark Troy'),
  ('eric-chen', 'Eric Chen'),
  ('evan-zeitler', 'Evan Zeitler'),
  ('graham-terhune', 'Graham Terhune'),
  ('jackson-freeman', 'Jackson Freeman'),
  ('jonathan-parr', 'Jonathan Parr'),
  ('josh-gouker', 'Josh Gouker'),
  ('kevin-olin', 'Kevin Olin'),
  ('kris-karvelas', 'Kris Karvelas'),
  ('lars-perlmutt', 'Lars Perlmutt'),
  ('matt-pizzuto', 'Matt Pizzuto'),
  ('matthew-ruterbories', 'Matthew Ruterbories'),
  ('max-perlmutt', 'Max Perlmutt'),
  ('meng-chen', 'Meng Chen'),
  ('patrick-vernon', 'Patrick Vernon'),
  ('pete-gannon', 'Pete Gannon'),
  ('peter-tawil', 'Peter Tawil'),
  ('robert-miller', 'Robert Miller'),
  ('robert-ratcliffe', 'Robert Ratcliffe'),
  ('ruchir-vora', 'Ruchir Vora'),
  ('ryan-kleeman', 'Ryan Kleeman'),
  ('stephen-whilden', 'Stephen Whilden'),
  ('stuart-beeson', 'Stuart Beeson'),
  ('william-scroggs', 'William Scroggs');

insert into public.player_emails (player_id, email) values
  ('adam-versenyi', 'anversen@email.unc.edu'),
  ('adam-zinn', 'adam@zinncompanies.com'),
  ('andrew-barrett', 'andrewcbarrett@yahoo.com'),
  ('andrew-kay', 'ajbkay87@gmail.com'),
  ('andy-galdi', 'andy.galdi@gmail.com'),
  ('cary-levine', 'clevine@unc.edu'),
  ('chris-petree', 'cebpetree@gmail.com'),
  ('clark-troy', 'mclarktroy@gmail.com'),
  ('eric-chen', 'ericchen@alumni.unc.edu'),
  ('evan-zeitler', 'ezeitler09@gmail.com'),
  ('graham-terhune', 'graham.terhune@gmail.com'),
  ('jackson-freeman', 'jacksonfreeman323@gmail.com'),
  ('jonathan-parr', 'jonbparr@gmail.com'),
  ('josh-gouker', 'jgouker5280@gmail.com'),
  ('kevin-olin', 'kdogolin@gmail.com'),
  ('kris-karvelas', 'karvelas@med.unc.edu'),
  ('lars-perlmutt', 'lperlmutt@gmail.com'),
  ('matt-pizzuto', 'pizzuto@med.unc.edu'),
  ('matthew-ruterbories', 'ruterbories@gmail.com'),
  ('max-perlmutt', 'm.perlmutt@gmail.com'),
  ('meng-chen', 'mengchen2000@hotmail.com'),
  ('patrick-vernon', 'pvernon@unc.edu'),
  ('pete-gannon', 'peter.gannon@duke.edu'),
  ('peter-tawil', 'pztawil@gmail.com'),
  ('robert-miller', 'rbmoup@gmail.com'),
  ('robert-ratcliffe', 'ratcliffe.rob@gmail.com'),
  ('ruchir-vora', 'ruchir.is@gmail.com'),
  ('ryan-kleeman', 'kleemanryanh@gmail.com'),
  ('stephen-whilden', 'stephenwhilden@gmail.com'),
  ('stuart-beeson', 'sbeeson1@gmail.com'),
  ('william-scroggs', 'wslax22@gmail.com');

insert into public.admins (email) values ('ezeitler09@gmail.com');

insert into public.matches (id, week, ord, home, away, outcome, winner, sets, source) values
  ('w1-01', 1, 1, 'eric-chen', 'evan-zeitler', 'completed', 'home', '[{"h": 6, "a": 3}, {"h": 6, "a": 1}]'::jsonb, 'import'),
  ('w1-02', 1, 2, 'andrew-barrett', 'jackson-freeman', null, null, '[]'::jsonb, 'app'),
  ('w1-03', 1, 3, 'ruchir-vora', 'ryan-kleeman', 'completed', 'away', '[{"h": 1, "a": 6}, {"h": 3, "a": 6}]'::jsonb, 'import'),
  ('w1-04', 1, 4, 'peter-tawil', 'patrick-vernon', 'completed', 'home', '[{"h": 6, "a": 1}, {"h": 6, "a": 1}]'::jsonb, 'import'),
  ('w1-05', 1, 5, 'stuart-beeson', 'meng-chen', 'completed', 'home', '[{"h": 6, "a": 1}, {"h": 6, "a": 7}, {"h": 1, "a": 0, "mtb": true}]'::jsonb, 'import'),
  ('w1-06', 1, 6, 'clark-troy', 'max-perlmutt', 'completed', 'home', '[{"h": 6, "a": 2}, {"h": 6, "a": 2}]'::jsonb, 'import'),
  ('w1-07', 1, 7, 'graham-terhune', 'lars-perlmutt', 'completed', 'home', '[{"h": 6, "a": 3}, {"h": 6, "a": 2}]'::jsonb, 'import'),
  ('w1-08', 1, 8, 'adam-zinn', 'cary-levine', 'completed', 'away', '[{"h": 3, "a": 6}, {"h": 1, "a": 6}]'::jsonb, 'import'),
  ('w1-09', 1, 9, 'pete-gannon', 'jonathan-parr', 'completed', 'away', '[{"h": 4, "a": 6}, {"h": 1, "a": 6}]'::jsonb, 'import'),
  ('w1-10', 1, 10, 'andy-galdi', 'matt-pizzuto', 'completed', 'home', '[{"h": 6, "a": 2}, {"h": 6, "a": 1}]'::jsonb, 'import'),
  ('w1-11', 1, 11, 'josh-gouker', 'stephen-whilden', null, null, '[]'::jsonb, 'app'),
  ('w1-12', 1, 12, 'robert-ratcliffe', 'matthew-ruterbories', 'completed', 'away', '[{"h": 0, "a": 6}, {"h": 6, "a": 2}, {"h": 5, "a": 10, "mtb": true}]'::jsonb, 'import'),
  ('w1-13', 1, 13, 'kris-karvelas', 'william-scroggs', null, null, '[]'::jsonb, 'app'),
  ('w1-14', 1, 14, 'adam-versenyi', 'chris-petree', 'completed', 'away', '[{"h": 3, "a": 6}, {"h": 0, "a": 6}]'::jsonb, 'import'),
  ('w1-15', 1, 15, 'andrew-kay', 'kevin-olin', null, null, '[]'::jsonb, 'app'),
  ('w1-16', 1, 16, 'robert-miller', null, null, null, '[]'::jsonb, 'app'),
  ('w2-01', 2, 1, 'evan-zeitler', 'ryan-kleeman', 'completed', 'home', '[{"h": 6, "a": 1}, {"h": 7, "a": 5}]'::jsonb, 'import'),
  ('w2-02', 2, 2, 'eric-chen', 'andrew-barrett', null, null, '[]'::jsonb, 'app'),
  ('w2-03', 2, 3, 'jackson-freeman', 'clark-troy', null, null, '[]'::jsonb, 'app'),
  ('w2-04', 2, 4, 'ruchir-vora', 'peter-tawil', null, null, '[]'::jsonb, 'app'),
  ('w2-05', 2, 5, 'patrick-vernon', 'meng-chen', null, null, '[]'::jsonb, 'app'),
  ('w2-06', 2, 6, 'robert-miller', 'matthew-ruterbories', null, null, '[]'::jsonb, 'app'),
  ('w2-07', 2, 7, 'robert-ratcliffe', 'josh-gouker', null, null, '[]'::jsonb, 'app'),
  ('w2-08', 2, 8, 'andy-galdi', 'william-scroggs', null, null, '[]'::jsonb, 'app'),
  ('w2-09', 2, 9, 'kris-karvelas', 'matt-pizzuto', null, null, '[]'::jsonb, 'app'),
  ('w2-10', 2, 10, 'adam-zinn', 'lars-perlmutt', 'completed', 'home', '[{"h": 7, "a": 6, "tb": 5}, {"h": 6, "a": 2}]'::jsonb, 'import'),
  ('w2-11', 2, 11, 'stuart-beeson', 'max-perlmutt', null, null, '[]'::jsonb, 'app'),
  ('w2-12', 2, 12, 'graham-terhune', 'jonathan-parr', null, null, '[]'::jsonb, 'app'),
  ('w2-13', 2, 13, 'cary-levine', 'pete-gannon', null, null, '[]'::jsonb, 'app'),
  ('w2-14', 2, 14, 'chris-petree', 'stephen-whilden', null, null, '[]'::jsonb, 'app'),
  ('w2-15', 2, 15, 'andrew-kay', 'adam-versenyi', null, null, '[]'::jsonb, 'app'),
  ('w2-16', 2, 16, 'kevin-olin', null, null, null, '[]'::jsonb, 'app'),
  ('w3-01', 3, 1, 'ryan-kleeman', 'stuart-beeson', null, null, '[]'::jsonb, 'app'),
  ('w3-02', 3, 2, 'jonathan-parr', 'clark-troy', null, null, '[]'::jsonb, 'app'),
  ('w3-03', 3, 3, 'matthew-ruterbories', 'kris-karvelas', null, null, '[]'::jsonb, 'app'),
  ('w3-04', 3, 4, 'andy-galdi', 'pete-gannon', null, null, '[]'::jsonb, 'app'),
  ('w3-05', 3, 5, 'andrew-kay', 'stephen-whilden', null, null, '[]'::jsonb, 'app'),
  ('w3-06', 3, 6, 'william-scroggs', 'chris-petree', null, null, '[]'::jsonb, 'app'),
  ('w3-07', 3, 7, 'kevin-olin', 'josh-gouker', null, null, '[]'::jsonb, 'app'),
  ('w3-08', 3, 8, 'matt-pizzuto', 'robert-miller', null, null, '[]'::jsonb, 'app'),
  ('w3-09', 3, 9, 'robert-ratcliffe', 'cary-levine', null, null, '[]'::jsonb, 'app'),
  ('w3-10', 3, 10, 'graham-terhune', 'adam-zinn', null, null, '[]'::jsonb, 'app'),
  ('w3-11', 3, 11, 'peter-tawil', 'jackson-freeman', null, null, '[]'::jsonb, 'app'),
  ('w3-12', 3, 12, 'eric-chen', 'patrick-vernon', null, null, '[]'::jsonb, 'app'),
  ('w3-13', 3, 13, 'evan-zeitler', 'andrew-barrett', null, null, '[]'::jsonb, 'app'),
  ('w3-14', 3, 14, 'max-perlmutt', 'meng-chen', null, null, '[]'::jsonb, 'app'),
  ('w3-15', 3, 15, 'lars-perlmutt', 'ruchir-vora', null, null, '[]'::jsonb, 'app'),
  ('w3-16', 3, 16, 'adam-versenyi', null, null, null, '[]'::jsonb, 'app'),
  ('w4-01', 4, 1, 'evan-zeitler', 'jackson-freeman', null, null, '[]'::jsonb, 'app'),
  ('w4-02', 4, 2, 'eric-chen', 'peter-tawil', null, null, '[]'::jsonb, 'app'),
  ('w4-03', 4, 3, 'andrew-barrett', 'ryan-kleeman', null, null, '[]'::jsonb, 'app'),
  ('w4-04', 4, 4, 'ruchir-vora', 'clark-troy', null, null, '[]'::jsonb, 'app'),
  ('w4-05', 4, 5, 'patrick-vernon', 'cary-levine', null, null, '[]'::jsonb, 'app'),
  ('w4-06', 4, 6, 'stuart-beeson', 'adam-zinn', null, null, '[]'::jsonb, 'app'),
  ('w4-07', 4, 7, 'graham-terhune', 'andy-galdi', null, null, '[]'::jsonb, 'app'),
  ('w4-08', 4, 8, 'pete-gannon', 'meng-chen', null, null, '[]'::jsonb, 'app'),
  ('w4-09', 4, 9, 'matt-pizzuto', 'max-perlmutt', null, null, '[]'::jsonb, 'app'),
  ('w4-10', 4, 10, 'josh-gouker', 'lars-perlmutt', null, null, '[]'::jsonb, 'app'),
  ('w4-11', 4, 11, 'jonathan-parr', 'robert-ratcliffe', null, null, '[]'::jsonb, 'app'),
  ('w4-12', 4, 12, 'robert-miller', 'kris-karvelas', null, null, '[]'::jsonb, 'app'),
  ('w4-13', 4, 13, 'matthew-ruterbories', 'andrew-kay', null, null, '[]'::jsonb, 'app'),
  ('w4-14', 4, 14, 'chris-petree', 'kevin-olin', null, null, '[]'::jsonb, 'app'),
  ('w4-15', 4, 15, 'william-scroggs', 'adam-versenyi', null, null, '[]'::jsonb, 'app'),
  ('w4-16', 4, 16, 'stephen-whilden', null, null, null, '[]'::jsonb, 'app'),
  ('w5-01', 5, 1, 'william-scroggs', 'andrew-kay', null, null, '[]'::jsonb, 'app'),
  ('w5-02', 5, 2, 'matthew-ruterbories', 'graham-terhune', null, null, '[]'::jsonb, 'app'),
  ('w5-03', 5, 3, 'andy-galdi', 'meng-chen', null, null, '[]'::jsonb, 'app'),
  ('w5-04', 5, 4, 'eric-chen', 'ruchir-vora', null, null, '[]'::jsonb, 'app'),
  ('w5-05', 5, 5, 'adam-zinn', 'josh-gouker', null, null, '[]'::jsonb, 'app'),
  ('w5-06', 5, 6, 'andrew-barrett', 'clark-troy', null, null, '[]'::jsonb, 'app'),
  ('w5-07', 5, 7, 'stuart-beeson', 'kevin-olin', null, null, '[]'::jsonb, 'app'),
  ('w5-08', 5, 8, 'patrick-vernon', 'lars-perlmutt', null, null, '[]'::jsonb, 'app'),
  ('w5-09', 5, 9, 'max-perlmutt', 'robert-ratcliffe', null, null, '[]'::jsonb, 'app'),
  ('w5-10', 5, 10, 'robert-miller', 'cary-levine', null, null, '[]'::jsonb, 'app'),
  ('w5-11', 5, 11, 'jonathan-parr', 'peter-tawil', null, null, '[]'::jsonb, 'app'),
  ('w5-12', 5, 12, 'stephen-whilden', 'adam-versenyi', null, null, '[]'::jsonb, 'app'),
  ('w5-13', 5, 13, 'matt-pizzuto', 'evan-zeitler', null, null, '[]'::jsonb, 'app'),
  ('w5-14', 5, 14, 'pete-gannon', 'kris-karvelas', null, null, '[]'::jsonb, 'app'),
  ('w5-15', 5, 15, 'ryan-kleeman', 'jackson-freeman', null, null, '[]'::jsonb, 'app'),
  ('w5-16', 5, 16, 'chris-petree', null, null, null, '[]'::jsonb, 'app');

insert into public.match_history (match_id, changed_by, summary) select id, 'Import', 'Imported from the original sheet' from public.matches where outcome is not null;
